In [5]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
def generate_sample(filename, s):
    #n = np.sum([1 for _ in open(filename)]) - 1 # number of records in file (excludes header)
    n = 2974335
    indices = np.arange(1, n + 1)
    skip = np.sort(np.random.choice(indices, size=n - s, replace=False)) # random indices to skip

    return pd.read_csv(filename, skiprows=skip)

In [7]:
us_acidents = generate_sample('https://www.dropbox.com/s/hsu5jcg4qcxui8b/US_Accidents_Dec19.csv?dl=1', 50000)

us_acidents.head(5)

      ID    Source  ...  Nautical_Twilight  Astronomical_Twilight
0   A-70  MapQuest  ...                Day                    Day
1  A-146  MapQuest  ...                Day                    Day
2  A-183  MapQuest  ...                Day                    Day
3  A-184  MapQuest  ...                Day                    Day
4  A-197  MapQuest  ...                Day                    Day

[5 rows x 49 columns]